version: "3.8"
networks:
  my_network:
    driver: bridge

services:
  mysql-db:
    image: mysql:8.0
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 10s
      retries: 5
    networks:
      - my_network

  backend:
    build: .
    container_name: backend-app
    restart: always
    environment:
      DB_URL: jdbc:mysql://mysql-db:3306/${MYSQL_DATABASE}
      DB_USER: ${MYSQL_USER}
      DB_PASSWORD: ${MYSQL_PASSWORD}
    depends_on:
      mysql-db:
        condition: service_healthy
    ports:
      - "8082:8080"
    networks:
      - my_network
    command: /bin/sh -c "until nc -z mysql-db 3306; do echo waiting for mysql-db; sleep 2; done; java -jar your-backend-app.jar"

  nginx:
    build: ./frontend
    container_name: nginx-proxy
    restart: always
    ports:
      - "8081:80"
    depends_on:
      - backend
    networks:
      - my_network

volumes:
    db_data:
